gneral-options:
  healthCheck: &healthCheck
    url: "http://www.gstatic.com/generate_204"
    lazy: true
    interval: 600
    timeout: 5000

proxy-providers-options:
  proxyProvidersCommon: &proxyProvidersCommon
    type: http
    interval: 3600
    health-check:
      enable: true
      <<: *healthCheck

rule-providers-options:
  ruleProvidersCommon: &ruleProvidersCommon
    type: http
    format: yaml
    interval: 10368000

proxy-groups-options:
  proxyGroupsCommon: &proxyGroupsCommon
    <<: *healthCheck
    max-failed-times: 3
  proxyGroupsInclude: &proxyGroupsInclude
    include-all: true
    <<: *proxyGroupsCommon
  proxyGroupsUse: &proxyGroupsUse
    use:
      - sub1
    <<: *proxyGroupsCommon
  proxyGroup: &proxyGroup
    proxies:
      - "ðŸ‡¦ðŸ‡· AR"
      - "ðŸ‡¦ðŸ‡º AU"
      - "ðŸ‡§ðŸ‡· BR"
      - "ðŸ‡¨ðŸ‡¦ CA"
      - "ðŸ‡©ðŸ‡ª DE"
      - "ðŸ‡ªðŸ‡¬ EG"
      - "ðŸ‡«ðŸ‡· FR"
      - "ðŸ‡­ðŸ‡° HK"
      - "ðŸ‡®ðŸ‡© ID"
      - "ðŸ‡®ðŸ‡³ IN"
      - "ðŸ‡¯ðŸ‡µ JP"
      - "ðŸ‡°ðŸ‡µ KP"
      - "ðŸ‡°ðŸ‡· KR"
      - "ðŸ‡²ðŸ‡´ MA"
      - "ðŸ‡²ðŸ‡½ MX"
      - "ðŸ‡²ðŸ‡¾ MY"
      - "ðŸ‡³ðŸ‡¬ NG"
      - "ðŸ‡³ðŸ‡± NL"
      - "ðŸ‡³ðŸ‡¿ NZ"
      - "ðŸ‡µðŸ‡­ PH"
      - "ðŸ‡µðŸ‡° PK"
      - "ðŸ‡·ðŸ‡º RU"
      - "ðŸ‡¸ðŸ‡¦ SA"
      - "ðŸ‡¸ðŸ‡¬ SG"
      - "ðŸ‡¹ðŸ‡­ TH"
      - "ðŸ‡¹ðŸ‡· TR"
      - "ðŸ‡¹ðŸ‡¼ TW"
      - "ðŸ‡ºðŸ‡¦ UA"
      - "ðŸ‡¬ðŸ‡§ UK"
      - "ðŸ‡ºðŸ‡¸ US"
      - "ðŸ‡»ðŸ‡³ VN"
  proxyGroupCombined: &proxyGroupCombined
    proxies:
      - "ðŸŒ DIRECT"
      - "ðŸš« REJECT"
      - "ðŸ«´ MANUAL"
      - "ðŸ§… TOR"
      - "ðŸ‡¦ðŸ‡· AR"
      - "ðŸ‡¦ðŸ‡º AU"
      - "ðŸ‡§ðŸ‡· BR"
      - "ðŸ‡¨ðŸ‡¦ CA"
      - "ðŸ‡©ðŸ‡ª DE"
      - "ðŸ‡ªðŸ‡¬ EG"
      - "ðŸ‡«ðŸ‡· FR"
      - "ðŸ‡­ðŸ‡° HK"
      - "ðŸ‡®ðŸ‡© ID"
      - "ðŸ‡®ðŸ‡³ IN"
      - "ðŸ‡¯ðŸ‡µ JP"
      - "ðŸ‡°ðŸ‡µ KP"
      - "ðŸ‡°ðŸ‡· KR"
      - "ðŸ‡²ðŸ‡´ MA"
      - "ðŸ‡²ðŸ‡½ MX"
      - "ðŸ‡²ðŸ‡¾ MY"
      - "ðŸ‡³ðŸ‡¬ NG"
      - "ðŸ‡³ðŸ‡± NL"
      - "ðŸ‡³ðŸ‡¿ NZ"
      - "ðŸ‡µðŸ‡­ PH"
      - "ðŸ‡µðŸ‡° PK"
      - "ðŸ‡·ðŸ‡º RU"
      - "ðŸ‡¸ðŸ‡¦ SA"
      - "ðŸ‡¸ðŸ‡¬ SG"
      - "ðŸ‡¹ðŸ‡­ TH"
      - "ðŸ‡¹ðŸ‡· TR"
      - "ðŸ‡¹ðŸ‡¼ TW"
      - "ðŸ‡ºðŸ‡¦ UA"
      - "ðŸ‡¬ðŸ‡§ UK"
      - "ðŸ‡ºðŸ‡¸ US"
      - "ðŸ‡»ðŸ‡³ VN"
      - "ðŸ³ï¸â€ðŸŒˆ Fusion"

log-level: silent
allow-lan: true
ipv6: false
unified-delay: true
tcp-concurrent: true
keep-alive-interval: 300
global-client-fingerprint: random
global-ua: clash.meta
profile:
  store-selected: true
  store-fake-ip: true

geodata-loader: standard
geo-auto-update: true
geo-update-interval: 168
geox-url:
  geoip: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://hub.gitmirror.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  dns-hijack:
    - any:53
  mtu: 1500

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80]
    TLS:
      ports: [443]
    QUIC:
      ports: [443]
  skip-domain:
    - '+.lan'
    - '+.local'
    - '+.localhost'
    - '+.home'

dns:
  enable: true
  prefer-h3: true
  ipv6: false
  use-hosts: true
  use-system-hosts: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - 'geosite:private'
    - 'geosite:cn'
    - '+.rustdesk.com'
  nameserver:
    - https://223.5.5.5/dns-query#skip-cert-verify=true
  proxy-server-nameserver:
    - https://9.9.9.9/dns-query#skip-cert-verify=true
  default-nameserver:
    - 223.5.5.5
    - 9.9.9.9
  fallback:
    - https://9.9.9.9/dns-query#skip-cert-verify=true
  fallback-filter:
    geoip: true
    geoip-code: CN
  nameserver-policy:
    'geosite:cn': https://223.5.5.5/dns-query#skip-cert-verify=true
    '+.rustdesk.com': https://223.5.5.5/dns-query#skip-cert-verify=true
    '+.openwrt.home': 192.168.2.1
    '+.nas.home': 192.168.2.1
    '+.rack.home': 192.168.2.1

proxy-providers:
  sub1:
    <<: *proxyProvidersCommon
    url: "https://sub1"
    path: ./proxy_providers/sub1.yaml
    proxy: "ðŸ‡¯ðŸ‡µ JP"

proxies:
  - name: "ðŸ§… TOR"
    type: socks5
    server: 127.0.0.1
    port: 9050
    udp: true
    ip-version: ipv4

proxy-groups:
  - name: "ðŸŒ DIRECT"
    type: select
    proxies:
      - DIRECT
  - name: "ðŸš« REJECT"
    type: select
    proxies:
      - REJECT
  - name: "ðŸ‡¦ðŸ‡· AR"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¦ðŸ‡·|é˜¿æ ¹å»·|argentina"
  - name: "ðŸ‡¦ðŸ‡º AU"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¦ðŸ‡º|æ¾³å¤§åˆ©äºš|æ¾³å¤§åˆ©äºž|australia"
  - name: "ðŸ‡§ðŸ‡· BR"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡§ðŸ‡·|å·´è¥¿|brazil"
  - name: "ðŸ‡¨ðŸ‡¦ CA"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¨ðŸ‡¦|åŠ æ‹¿å¤§|canada"
  - name: "ðŸ‡©ðŸ‡ª DE"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡©ðŸ‡ª|å¾·å›½|å¾·åœ‹|æŸæž—|æ…•å°¼é»‘|germany"
  - name: "ðŸ‡ªðŸ‡¬ EG"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡ªðŸ‡¬|åŸƒåŠ|egypt"
  - name: "ðŸ‡«ðŸ‡· FR"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡«ðŸ‡·|æ³•å›½|æ³•åœ‹|ç¦å…°å…‹|ç¦è˜­å…‹|french"
  - name: "ðŸ‡­ðŸ‡° HK"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡­ðŸ‡°|é¦™æ¸¯|hongkong"
  - name: "ðŸ‡®ðŸ‡© ID"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡®ðŸ‡©|å°å°¼|indonesia"
  - name: "ðŸ‡®ðŸ‡³ IN"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡®ðŸ‡³|å°åº¦|india"
  - name: "ðŸ‡¯ðŸ‡µ JP"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¯ðŸ‡µ|æ—¥æœ¬|japan"
  - name: "ðŸ‡°ðŸ‡µ KP"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡°ðŸ‡µ|æœé²œ|æœé®®"
  - name: "ðŸ‡°ðŸ‡· KR"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡°ðŸ‡·|éŸ©å›½|éŸ“åœ‹"
  - name: "ðŸ‡²ðŸ‡´ MA"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡²ðŸ‡´|æ¾³é—¨|æ¾³é–€|maco"
  - name: "ðŸ‡²ðŸ‡½ MX"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡²ðŸ‡½|å¢¨è¥¿å“¥|mexico"
  - name: "ðŸ‡²ðŸ‡¾ MY"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡²ðŸ‡¾|é©¬æ¥è¥¿äºš|é¦¬ä¾†è¥¿äºž|malaysia"
  - name: "ðŸ‡³ðŸ‡¬ NG"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡³ðŸ‡¬|å°¼æ—¥åˆ©äºš|nigeria"
  - name: "ðŸ‡³ðŸ‡± NL"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡³ðŸ‡±|è·å…°|è·è˜­|netherlands"
  - name: "ðŸ‡³ðŸ‡¿ NZ"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡³ðŸ‡¿|æ–°è¥¿å…°|æ–°è¥¿è˜­|zeeland"
  - name: "ðŸ‡µðŸ‡­ PH"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡µðŸ‡­|è²å¾‹å®¾|è²å¾‹è³“|philippines"
  - name: "ðŸ‡µðŸ‡° PK"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡µðŸ‡°|å·´åŸºæ–¯å¦|pakistan"
  - name: "ðŸ‡·ðŸ‡º RU"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡·ðŸ‡º|ä¿„ç½—æ–¯|ä¿„ç¾…æ–¯|russia"
  - name: "ðŸ‡¸ðŸ‡¦ SA"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¸ðŸ‡¦|æ²™ç‰¹|arabia"
  - name: "ðŸ‡¸ðŸ‡¬ SG"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¸ðŸ‡¬|æ–°åŠ å¡|singapore"
  - name: "ðŸ‡¹ðŸ‡­ TH"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¹ðŸ‡­|æ³°å›½|æ³°åœ‹|Thailand"
  - name: "ðŸ‡¹ðŸ‡· TR"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¹ðŸ‡·|åœŸè€³å…¶|turkey"
  - name: "ðŸ‡¹ðŸ‡¼ TW"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¹ðŸ‡¼|å°æ¹¾|è‡ºç£|taiwan"
  - name: "ðŸ‡ºðŸ‡¦ UA"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡ºðŸ‡¦|ä¹Œå…‹å…°|çƒå…‹è˜­|ukrainian"
  - name: "ðŸ‡¬ðŸ‡§ UK"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡¬ðŸ‡§|è‹±|è‹±åœ‹|england|kingdom|britsh"
  - name: "ðŸ‡ºðŸ‡¸ US"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡ºðŸ‡¸|ç¾Žå›½|ç¾Žåœ‹|è¥¿é›…å›¾|è¥¿é›…åœ–|æ´›æ‰çŸ¶|æ´›æ‰ç£¯|è‰¾æ–¯æœ¬|america|states|seattle|angeles|ashburn"
  - name: "ðŸ‡»ðŸ‡³ VN"
    <<: *proxyGroupsInclude
    type: select
    filter: "(?i)ðŸ‡»ðŸ‡³|è¶Šå—|vietnam"
  - name: "ðŸ³ï¸â€ðŸŒˆ Fusion"
    <<: *proxyGroupsInclude
    type: select
    exclude-filter: "ðŸ§…"
  - name: "ðŸ«´ MANUAL"
    type: select
    proxies:
      - "ðŸŒ DIRECT"
      - "ðŸš« REJECT"
      - "ðŸ§… TOR"
      - "ðŸ‡¦ðŸ‡· AR"
      - "ðŸ‡¦ðŸ‡º AU"
      - "ðŸ‡§ðŸ‡· BR"
      - "ðŸ‡¨ðŸ‡¦ CA"
      - "ðŸ‡©ðŸ‡ª DE"
      - "ðŸ‡ªðŸ‡¬ EG"
      - "ðŸ‡«ðŸ‡· FR"
      - "ðŸ‡­ðŸ‡° HK"
      - "ðŸ‡®ðŸ‡© ID"
      - "ðŸ‡®ðŸ‡³ IN"
      - "ðŸ‡¯ðŸ‡µ JP"
      - "ðŸ‡°ðŸ‡µ KP"
      - "ðŸ‡°ðŸ‡· KR"
      - "ðŸ‡²ðŸ‡´ MA"
      - "ðŸ‡²ðŸ‡½ MX"
      - "ðŸ‡²ðŸ‡¾ MY"
      - "ðŸ‡³ðŸ‡¬ NG"
      - "ðŸ‡³ðŸ‡± NL"
      - "ðŸ‡³ðŸ‡¿ NZ"
      - "ðŸ‡µðŸ‡­ PH"
      - "ðŸ‡µðŸ‡° PK"
      - "ðŸ‡·ðŸ‡º RU"
      - "ðŸ‡¸ðŸ‡¦ SA"
      - "ðŸ‡¸ðŸ‡¬ SG"
      - "ðŸ‡¹ðŸ‡­ TH"
      - "ðŸ‡¹ðŸ‡· TR"
      - "ðŸ‡¹ðŸ‡¼ TW"
      - "ðŸ‡ºðŸ‡¦ UA"
      - "ðŸ‡¬ðŸ‡§ UK"
      - "ðŸ‡ºðŸ‡¸ US"
      - "ðŸ‡»ðŸ‡³ VN"
      - "ðŸ³ï¸â€ðŸŒˆ Fusion"
  - name: "ðŸš˜ Auto"
    type: url-test
    tolerance: 100
    max-failed-times: 3
    <<: *proxyGroup
  - name: "ðŸ”™ Fallback"
    type: fallback
    url: 'https://www.gstatic.com/generate_204'
    max-failed-times: 3
    <<: *proxyGroup
  - name: "ðŸ”Š ADS"
    type: select
    proxies:
      - "ðŸŒ DIRECT"
      - "ðŸš« REJECT"
      - "ðŸ«´ MANUAL"
  - name: "ðŸ¤– AI"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸŽ Apple"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ‡¬ Google"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ§ª YouTube"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ¥… Netflix"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ­ Disney"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ‘Œ HBO"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ§™ðŸ¿â€â™€ï¸ Twitch"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ¦ Twitter"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ“² Telegram"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸš‚ Steam"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸªŸ Microsoft"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ“ˆ IPinfo"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ‘‚ Spotify"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸ€„ Manchuria"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸªœ Proxy"
    type: select
    <<: *proxyGroupCombined
  - name: "ðŸŸ Leakage"
    type: select
    <<: *proxyGroupCombined

rules:
  - GEOIP,PRIVATE,ðŸŒ DIRECT,no-resolve
  - GEOSITE,private,ðŸŒ DIRECT
  - GEOSITE,category-ads-all,ðŸ”Š ADS
  - IP-CIDR,9.9.9.9/32,ðŸŒ DIRECT,no-resolve
  - GEOSITE,speedtest,ðŸ“ˆ IPinfo
  - DOMAIN,fast.com,ðŸ“ˆ IPinfo
  - DOMAIN,check.torproject.org,ðŸ“ˆ IPinfo
  - DOMAIN-SUFFIX,myip.la,ðŸ“ˆ IPinfo
  - DOMAIN-SUFFIX,ipip.net,ðŸ“ˆ IPinfo
  - DOMAIN-SUFFIX,ipinfo.io,ðŸ“ˆ IPinfo
  - GEOSITE,google,ðŸ‡¬ Google
  - GEOSITE,youtube,ðŸ§ª YouTube
  - GEOSITE,netflix,ðŸ¥… Netflix
  - GEOSITE,disney,ðŸ­ Disney
  - GEOSITE,hbo,ðŸ‘Œ HBO
  - GEOSITE,openai,ðŸ¤– AI
  - GEOSITE,anthropic,ðŸ¤– AI
  - GEOSITE,twitch,ðŸ§™ðŸ¿â€â™€ï¸ Twitch
  - GEOSITE,twitter,ðŸ¦ Twitter
  - GEOSITE,telegram,ðŸ“² Telegram
  - GEOSITE,spotify,ðŸ‘‚ Spotify
  - GEOSITE,microsoft@cn,ðŸŒ DIRECT
  - GEOSITE,microsoft,ðŸªŸ Microsoft
  - GEOSITE,apple@cn,ðŸŒ DIRECT
  - GEOSITE,apple,ðŸŽ Apple
  - GEOSITE,steam@cn,ðŸŒ DIRECT
  - GEOSITE,steam,ðŸš‚ Steam
  - GEOSITE,bilibili,ðŸ€„ Manchuria
  - GEOSITE,zhihu,ðŸ€„ Manchuria
  - GEOSITE,douban,ðŸ€„ Manchuria
  - GEOSITE,smzdm,ðŸ€„ Manchuria
  - DOMAIN-SUFFIX,linux.do,ðŸŒ DIRECT
  - DOMAIN-SUFFIX,rustdesk.com,ðŸŒ DIRECT
  - PROCESS-PATH-REGEX,.*rustdesk,ðŸŒ DIRECT
  - GEOIP,CN,ðŸŒ DIRECT,no-resolve
  - GEOSITE,cn,ðŸŒ DIRECT
  - GEOSITE,geolocation-!cn,ðŸªœ Proxy
  - MATCH,ðŸŸ Leakage